
name: Build and Push Docker Image to Google Cloud Artifact Registry  

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image to Google Artifact Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          gcr.io/manim-videos/captioning:latest
          gcr.io/manim-videos/captioning:${{ github.sha }}
      env:
        DOCKER_BUILDKIT: 1
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_SERVICE_KEY }} 
